#!/usr/bin/env bash
if test "$BASH" = "" || "$BASH" -uc 'a=();true "${a[@]}"' 2>/dev/null; then
    # Bash 4.4, Zsh
    set -euo pipefail
else
    # Bash 4.3 and older chokes on empty arrays with set -u.
    set -eo pipefail
fi
shopt -s nullglob globstar

declare -A F_OPTIONS

F_OPTIONS["skelpath"]="/etc/skel"
F_OPTIONS["masterkeys"]="https://two.frame.hosting/_authkeys"


function setup_skel {

  if [[ "$(whoami)" != "root" ]]; then
    echo "unable to become root user"
    exit 1
  fi

  local key_folder="${F_OPTIONS[skelpath]}/.ssh"
  local key_file="${key_folder}/authorized_keys"

  output "Checking skel dirs exist"
  mkdir -p "${key_folder}"
  mkdir -p "${key_folder}/additional_keys"

  output "Downloading new master key file"
  curl "${F_OPTIONS[masterkeys]}" > "${key_file}"

  output "Setting skel key permissions"
  chmod 600 "${key_file}"
  chmod 700 "${key_folder}"

  output "exiting root"

  exit 0;

}

function FST_RUN_SELF {

  output "RUNNING SKEL as $(whoami)"
  #setup_skel;
}
